id: I6CD1FFEC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T04:06:26+00:00'
last_modified: '2022-06-08T08:42:52.267854+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18901
  title: ཀྲུང་གོའི་གུང་ཁྲན་ཏང་གི་སྐབས་བཅོ་བརྒྱད་པའི་ཀྲུང་དབྱང་ཨུ་ཡོན་ལྷན་ཁང་གི་ཚང་འཛོམས་གྲོས་ཚོགས་ཐེངས་བཞི་པའི་ཡིག་ཆ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    08BC:
      image_group_id: I8LS18903
      title: ''
      total_pages: 148
      order: 1
      base_file: 08BC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
