id: opecha:P009113
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18901
  title: ཀྲུང་གོའི་གུང་ཁྲན་ཏང་གི་སྐབས་བཅོ་བརྒྱད་པའི་ཀྲུང་དབྱང་ཨུ་ཡོན་ལྷན་ཁང་གི་ཚང་འཛོམས་གྲོས་ཚོགས་ཐེངས་བཞི་པའི་ཡིག་ཆ་ཕྱོགས་བསྒྲིགས།
  volume: ''
  author: ''
